services:
  app:
    build: .
    container_name: flask-app
    volumes:
      - ./app:/app
    expose:
      - "5000"
    restart: unless-stopped
    # networks は削除（デフォルトネットワークを使用）

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/static-site:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN}
      - DOMAIN_WWW=${DOMAIN_WWW}
    depends_on:
      - app
    restart: unless-stopped
    # networks は削除（デフォルトネットワークを使用）
    command: "/bin/sh -c 'envsubst \$$DOMAIN,\$$DOMAIN_WWW < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # networks は削除（デフォルトネットワークを使用）

# networks セクションも削除（デフォルトで十分）